// Signs the Android release build with a key of your own, never the debug key every Expo
// template ships (it's public, so anyone could sign an "update" that installs over the app).
// android/ is generated by expo prebuild, so the change goes in here, not in build.gradle.
// The key comes from a properties file named at build time (README, "Standalone APK"); a
// release build without one stops instead of falling back to the debug key. Debug builds
// and the dev client are untouched. EAS builds sign with their own credentials: skipped there.
const { withAppBuildGradle } = require("expo/config-plugins");

const MARKER = "plexbie.signing";
const HELP = "see the README, Standalone APK";

// Reads the key's properties file at configuration time; the check that stops a release
// build runs once Gradle knows which tasks it will run, so debug builds never need the file.
const PREAMBLE = `// Plexbie: a release build is signed with your own key, from a properties file (storeFile,
// storePassword, keyAlias, keyPassword; storeFile absolute or beside the file) named by
// -Pplexbie.signing=/path/to/file or PLEXBIE_SIGNING. Without one a release build stops
// rather than sign with the public debug key. Added by plugins/withReleaseSigning.js.
def plexbieSigning = null
def plexbieSigningProblem = null
def plexbieFile = { String path, File base ->
    path = path.trim()
    if (path.startsWith('~/')) path = System.getProperty('user.home') + path.substring(1)
    def f = new File(path)
    f.isAbsolute() ? f : new File(base, path)
}
def plexbieSigningPath = (findProperty('${MARKER}') ?: System.getenv('PLEXBIE_SIGNING') ?: '').toString()
if (!plexbieSigningPath.trim()) {
    plexbieSigningProblem = "no key given. Build with -P${MARKER}=/path/to/signing.properties (or set PLEXBIE_SIGNING); ${HELP}."
} else {
    def signingFile = plexbieFile(plexbieSigningPath, rootDir.parentFile)
    if (!signingFile.isFile()) {
        plexbieSigningProblem = "-P${MARKER} names \${signingFile}, which isn't there; ${HELP}."
    } else {
        def props = new Properties()
        signingFile.withInputStream { props.load(it) }
        def missing = ['storeFile', 'storePassword', 'keyAlias', 'keyPassword'].findAll { !props.getProperty(it) }
        if (missing) {
            plexbieSigningProblem = "\${signingFile} (-P${MARKER}) has no \${missing.join(', ')}; ${HELP}."
        } else {
            def store = plexbieFile(props.getProperty('storeFile'), signingFile.parentFile)
            if (!store.isFile()) {
                plexbieSigningProblem = "the keystore storeFile names in \${signingFile} (-P${MARKER}) isn't there; ${HELP}."
            } else {
                plexbieSigning = [storeFile: store, storePassword: props.getProperty('storePassword'),
                                  keyAlias: props.getProperty('keyAlias'), keyPassword: props.getProperty('keyPassword')]
            }
        }
    }
}
gradle.taskGraph.whenReady { graph ->
    if (plexbieSigningProblem && graph.allTasks.any { it.project == project && it.name.contains('Release') }) {
        throw new GradleException("Not building the release: \${plexbieSigningProblem}")
    }
}

`;

/** The release signing config, empty (so nothing is signed) until the file above is read. */
function releaseConfig(indent) {
  return [
    "release {",
    "    // Your own key, read from the file -Pplexbie.signing names (top of this file).",
    "    if (plexbieSigning) {",
    "        storeFile plexbieSigning.storeFile",
    "        storePassword plexbieSigning.storePassword",
    "        keyAlias plexbieSigning.keyAlias",
    "        keyPassword plexbieSigning.keyPassword",
    "    }",
    "}",
  ].map((line) => indent + line).join("\n") + "\n";
}

function anchorMissing(what) {
  return new Error(
    `withReleaseSigning: android/app/build.gradle no longer has ${what} where expected, so the release ` +
      "build can't be given its own key. Update plugins/withReleaseSigning.js for the new template.",
  );
}

/** Rewrites the generated android/app/build.gradle; a file already rewritten comes back as it is. */
function addReleaseSigning(contents) {
  if (contents.includes(MARKER)) return contents;

  const android = /\nandroid \{\n/;
  if (!android.test(contents)) throw anchorMissing("the `android {` block");
  let out = contents.replace(android, (m) => `\n${PREAMBLE}${m.slice(1)}`);

  const debugConfig = /(\n( *)signingConfigs \{\n *debug \{\n[^{}]*?\n *\}\n)/;
  const found = out.match(debugConfig);
  if (!found) throw anchorMissing("signingConfigs { debug { … } }");
  out = out.replace(debugConfig, (m) => m + releaseConfig(`${found[2]}    `));

  const releaseType = /(\n *buildTypes \{[\s\S]*?\n *release \{[^{}]*?)signingConfig signingConfigs\.debug\b/;
  if (!releaseType.test(out)) throw anchorMissing("signingConfig signingConfigs.debug in the release build type");
  return out.replace(releaseType, (_, head) => `${head}signingConfig signingConfigs.release`);
}

function withReleaseSigning(config) {
  if (process.env.EAS_BUILD === "true") return config;
  return withAppBuildGradle(config, (config) => {
    if (config.modResults.language !== "groovy") {
      throw new Error("withReleaseSigning: android/app/build.gradle isn't Groovy, so the release key can't be added.");
    }
    config.modResults.contents = addReleaseSigning(config.modResults.contents);
    return config;
  });
}

module.exports = withReleaseSigning;
module.exports.addReleaseSigning = addReleaseSigning;
